name: Build and Publish .NET Package

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DOTNET_VERSION: '9.0.100'

jobs:
  build-and-push-image:
    name: Build app and push Docker image
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Get tag
        id: get-tag
        run: |
          VERSION=$(echo "${GITHUB_REF##*/}")
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish

      - name: Zip .NET app
        run: |
          zip -r9 ./${{ github.event.repository.name }}-${{ env.VERSION }}.zip ./publish

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload --file ./src/${{ github.event.repository.name }}-${{ env.VERSION }}.zip --account-name cicdfuncapptest --container-name func-releases --auth-mode login