
name: Create and publish a Docker image

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-image:
    name: Build app and push Docker image
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login -n ${{ vars.ACR_NAME }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ vars.ACR_NAME }}/${{ env.IMAGE_NAME }}

      - name: Get tag
        id: get-tag
        run: |
          VERSION=$(echo "${GITHUB_REF##*/}")
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          push: true
          tags: ${{ vars.ACR_NAME }}/${{ github.event.repository.name }}:latest,${{ vars.ACR_NAME }}/${{ github.event.repository.name }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AZURE_DEVOPS_PAT=${{ secrets.AZURE_DEVOPS_PAT }}