name: "Semantic PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    if: github.actor!= 'grantonai-cicd-bot[bot]'
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GRANTON_CICD_APP_ID }}
          private-key: ${{ secrets.GRANTON_CICD_APP_SECRET }}
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}